#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

#index:
#  path: /
#  defaults: {_controller: 'App\Controller\TestController::test'}

# Depends on sensio/framework-extra-bundle, doctrine/annotations, and doctrine/cache
#   install with composer req sensio/framework-extra-bundle annot
controllers:
    resource: ../src/Controller/
    type: annotation
